spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/gms
    password: earthman
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'